#!/usr/bin/bash
#Author: WZJ
#Created Time: 2021/08
#Script Description: Hadoop Control script

function start()
{

 echo "=================== 启动 hadoop 集群 ==================="
 echo "--------------- 启动 hdfs ---------------"
 ssh hadoop01 "/opt/hadoop-2.7.2/sbin/start-dfs.sh"
 echo "--------------- 启动 yarn ---------------"
 ssh hadoop02 "/opt/hadoop-2.7.2/sbin/start-yarn.sh"
 echo "--------------- 启动 historyserver ---------------"
 ssh hadoop03 "/opt/hadoop-2.7.2/bin/mapred --daemon start historyserver"

}

function stop()
{

 echo "=================== 关闭 hadoop 集群 ==================="
 echo "--------------- 关闭 historyserver ---------------"
 ssh hadoop01 "/opt/hadoop-2.7.2/bin/mapred --daemon stop historyserver"
 echo "--------------- 关闭 yarn ---------------"
 ssh hadoop02 "/opt/hadoop-2.7.2/sbin/stop-yarn.sh"
 echo "--------------- 关闭 hdfs ---------------"
 ssh hadoop03 "/opt/hadoop-2.7.2/sbin/stop-dfs.sh"
 
}

function status()
{

for host in hadoop01 hadoop02 hadoop03
do
 echo =============== $host ===============
 ssh $host "$JAVA_HOME/bin/jps"
done

}

case $1 in
"start")
start
;;
"stop")
stop
;;
"restart")
stop
start
;;
"status")
status
;;
*)
echo "Hadoop Control Scrip Usage: hadoopctl [start|stop|restart|status]"
;;
esac
